### PR TITLE
Footer update

### PR DESCRIPTION
**Pull request by mgrienauer**
Updated footer to appear at bottom of page and aligned text right with padding of 24px. The inner text was originally wrapped in a container but I removed it because it didn't look like it was matching the style of the Figma file. I can undo the padding and put it back in the container though.

### CODE REVIEW

**Review by Chris-Boe — CHANGES_REQUESTED** [review]
Just gotta get rid of all the extra files/changes 😄

**Comment by mgrienauer** [comment]
Ok, I used git rebase and removed that init commit that seemed to be changing all those files. I think that I did it correctly, but mind taking a look? First time using rebase.

**Comment by Chris-Boe** [comment]
I'm on kind of a wide-screen but I'm seeing a bit of a gap between the footer and the left nav when i have the browser at full screen
image

**Comment by mgrienauer** [comment]
Ah, ok I gotta take another look at it tomorrow.

**Review by Chris-Boe — APPROVED** [review]

**Pull request merged**
