### PR TITLE
fixed lease dates in manage tenant view

### LINKED ISSUE #580: Tenant info does not show correct lease dates
**Describe the bug**
In the TenantView, the lease start and end dates always show today's current date, regardless of the actual dates saved in the database.

**To Reproduce**
1. Sign in as Admin
2. Click on 'Manage Tenants'
3. Select a tenant that has a lease
4. See the improper dates

This is due to this code, which improperly tries to access `dateTimeStart` and `dateTimeEnd` through the tenant's property and ends up creating a new `Date` instance:
https://github.com/codeforpdx/dwellingly-app/blob/5c11ab10a48ebad91bd792b1f67f5eeca0f88ae6/src/views/Tenant/TenantView.jsx#L212-L213

**Expected behavior**
The lease start and end dates should reflect what is actually saved in the database.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by yunnie**
### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR.
Closes #580 and #578

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? No
Any special requirements to test? No

### Please make sure you've attempted to meet the following coding standards
- [ x] Code builds successfully
- [ x] Code has been tested and does not produce errors
- [ x] Code is readable and formatted
- [ x] There isn't any unnecessary commented-out code
- [ x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Review by aedwardg — DISMISSED** [review]
Looks like this works!

**Comment by yunnie** [comment]
This is related to #578. So I think it' better to just make one pull request that covers both issues.

**Comment by devon-wolf** [comment]
I'm going through issues this morning, and I'm wondering:  does this also resolve #579 (tenants should not be created with incomplete lease/property info)?  

If this is assuming a default "not housed" status when a tenant is being created it seems like that issue becomes redundant/outdated. 

(If we'd like an explicit assignment  to 'unhoused' in the add tenant form, though, I'd be happy to update the issue and work on that. It would add clarity from the user perspective even if we're already handling it underneath.)

**Comment by aedwardg** [comment]
@devon-wolf 

No, the issue in #579 is completely separate from this.  This PR (and its corresponding issue) are regarding the fact that lease dates displayed on the front end always showed today's date for both the lease start and end date -- even if the correct dates were stored on the back end.

The issue described in #579 has to do with lease creation and property assignment failing silently due to the front end allowing a user to create a new tenant without the information the back end needs for saving lease/property information to the database.

The front end _should_ (and does) allow a tenant to be created with either:
1. No property/lease information (unhoused tenant); or
2. With property/lease information (housed tenant)

The problem is that for option 2 (housed tenant), the following information _must_ be provided for the lease creation and property assignment to be successful:
- Lease start and end dates; **and**
- The property ID 

All other property/lease fields in the `TenantView` are optional.

Currently, when a user chooses to Add a Tenant, they can provide other lease/property options and neither of the above requirements, or just one of the above requirements and then hit "SAVE".  This results in a successful tenant creation, but the lease creation and property assignment never happen and the user has no idea that they were unsuccessful.

There are several ways to handle this; I suggested more form validation on the front end, but perhaps we should discuss it with Hugh at Wednesday's meeting to see what he prefers.

**Comment by yunnie** [comment]
An alternative would be to just not return Property, Unit Number and Lease Dates at all. But I used "Unhoused Tenant" and "Not Applicable" (though it could also be "Not Available") to indicate that the information is missing.

**Review by Chris-Boe — APPROVED** [review]
Nice work!

**Pull request merged**
