### PR TITLE
Add prettier automatic linting

### LINKED ISSUE #95: FRONTEND: Add automatic eslint formatting
- [x] Add formatting rules
- [x] Have these rules get applied ~on save~ on commit

### PR DESCRIPTION
**Pull request by Chris-Boe**
A pre-commit hook will now format files when you commit them

Using an eslint on save formatter would require ejection from Create-React-App which I didn't feel necessary for this change

### CODE REVIEW

**Comment by KentShikama** [comment]
Note this conflicts with https://github.com/codeforpdx/dwellingly-app/pull/177

**Comment by Chris-Boe** [comment]
> Note this conflicts with #177

@KentShikama how so?

**Comment by KentShikama** [comment]
That is an old comment. I don't think it still applies.

**Comment by Chris-Boe** [comment]
> That is an old comment. I don't think it still applies.

Okay! I didn't change anything in the PR though (just gotta keep rebasing it as other PR's are merged) so if you still have a concern, let me know

**Comment by Chris-Boe** [comment]
Think we're going to pass on this linter for now, we can leave the branch around and revisit it if we need to!

**Pull request closed without merging**
