### PR TITLE
Create property error msg

### LINKED ISSUE #740: Creating property with a name that already exists does not display the error message
**Describe the bug**
A property name is unique.
When creating a property with a name that already exists. The error message is not displayed. Instead the user sees that response status code, instead of the responses error message.

**To Reproduce**
1. Go to add property
2. fill in the form and provide a property name with one that already exists in the system
3. submit form

**Expected behavior**
I'd expect an error message that says the property name already exists.

**Screenshots**
Screen Shot 2021-11-14 at 8 44 43 AM

### PR DESCRIPTION
**Pull request by yunnie**
### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR.
Closes #740

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? No
Any special requirements to test? No

### Please make sure you've attempted to meet the following coding standards
- [ x] Code builds successfully
- [ x] Code has been tested and does not produce errors
- [ x] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [x ] There aren't any unnecessary commits or files changed

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Comment by yunnie** [comment]
I'm looking for feedback. I can either convert the `error.response.data` from `Axios` to a string in the `App.jsx` file. This would change the behavior for error messages for the entire app. That code is currently commented out.

Or I can handle the `error.response.data` from the `AddProperty/index.jsx` file. In this case, two Toast Error messages will be displayed. One from `App.jsx` which will give the HTTP error response code, and the other which will read `"name": ["already taken"]` Personally, I think having some useful feedback like "name already taken" is a bit more helpful to the user.

**Comment by Chris-Boe** [comment]
> I'm looking for feedback. I can either convert the `error.response.data` from `Axios` to a string in the `App.jsx` file. This would change the behavior for error messages for the entire app. That code is currently commented out.
> 
> Or I can handle the `error.response.data` from the `AddProperty/index.jsx` file. In this case, two Toast Error messages will be displayed. One from `App.jsx` which will give the HTTP error response code, and the other which will read `"name": ["already taken"]` Personally, I think having some useful feedback like "name already taken" is a bit more helpful to the user.

Thanks for doing this! I usually prefer the components themselves to handle 400 level errors like this, so they can convert the Toast message to something readable, insert additional data, or have a side-effect to recover from the error. This also would've been the only way to really have a good experience with the old API because different API's returned different responses when there was an error. Is that updated now with Ruby so that all API's return a consistent structure for an error?

If that's the case, I think we can have the global Axios handler prettify and show a toast with the error message while still handing the error message and status code down to the component level so the component can add extra functionality in a catch statement.

**Comment by yunnie** [comment]
I'm a Ruby and Rails noob, but I would think that the error messages from Rails would be pretty consistent in structure and form. I just can't see the Rails core team allowing inconsistently structured error messages. But I would defer to someone with more experience with Rails.

**Comment by yunnie** [comment]
@Chris-Boe Thank you for the suggestion on how to display the back-end validation error in the form via Formik. I ended up adding a parameter to the `apiCall` function in the `App.jsx` file for Formik's `setFieldError`. I kept the Toast message, just so that people know that there is an error. I also made sure that the form does not reset if there is a backend validation error.

**Review by NickSchimek — APPROVED** [review]

**Pull request merged**
