### PR TITLE
297 edit UI

### LINKED ISSUE #297: Documentation issue: Edit UI to meet accessibility standards (WIP)
**Purpose**
What will this feature provide?
Meet Accessibility standards outline in #178 

**Proposed Solution**
Go through this doc and either fix them where possible or write up additional issues for sections that would require substantial work
https://www.figma.com/proto/4Tjz7YVGoiCEFX8emLS80E/Accessibility-Design-Audit?node-id=26%3A10&viewport=116%2C1179%2C0.25&scaling=min-zoom

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ]

**Additional context**
This issue is mostly a placeholder until I can take a deeper dive into the audit doc

### PR DESCRIPTION
**Pull request by Protopaco**
### What issue is this solving?
closes #297

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? No
Any special requirements to test? No

- I made some adjustments to the color properties in the base 'variables.scss' adding darker version of the dashboard module backgrounds
- adjusted navigationMenu active link color from black to yellow, to increase color contrast
- increase navigationMenu text size & padding for readability
- adjusted formatting of form text to increase size and contrast in addTenant, addProperty, and changePassword
- adjusted header & navigationMenu background colors for more contrast with white text
- adjusted width of 'Assign Property Managers' SearchPane to 250px

All of this was done with small adjustments to individual variables, so shouldn't effect any larger functionality.  I did my best to keep the styling consistent to what was there before, just making adjustments for readability.  If you have any further adjustments, or alternative colors I can go back and make those adjustments.  

I was having some minor issues with my hosted backend (401 errors) so I wasn't able to interact with all parts of the app, so I might have missed some elements.  Feel free to let me know what I missed.

I hope that is enough information.  I'm excited to learn more about this app, and hopefully make more meaningful PRs in the future.

Thank you!

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Comment by Chris-Boe** [comment]
I like the majority of these changes, especially the bigger text and changes to buttons and other interactive elements. We should demo this to the team so we can get a general consensus!
Also I was curious why package-lock.json had such a big diff? I think we could just drop the changes to that file in this PR since it's unrelated

**Comment by Protopaco** [comment]
@Chris-Boe,  I'm actually shocked about the package-lock.json.  I'm not at all sure how I managed 22,000 changes.  This was my first dip into the codebase, and I didn't have the best understanding of the mechanics at that point.  

I  agree that it will probably be best to ditch these changes all together.  When there is an updated design, and you would like me to make the adjustments, I can start from scratch at that time.

Thanks!

**Comment by Chris-Boe** [comment]
> @Chris-Boe, I'm actually shocked about the package-lock.json. I'm not at all sure how I managed 22,000 changes. This was my first dip into the codebase, and I didn't have the best understanding of the mechanics at that point.
> 
> I agree that it will probably be best to ditch these changes all together. When there is an updated design, and you would like me to make the adjustments, I can start from scratch at that time.
> 
> Thanks!

I think you have some good improvements in this PR! Let's see if we can demo it to Hugh and the team to get some more feedback and start a conversation about making things more accessible

**Comment by DaveTrost** [comment]
@Protopaco @Chris-Boe 
Put this PR on the list of things to bring up at next Wednesday's meeting. I'll try to help remember as well!

**Comment by DaveTrost** [comment]
@Protopaco, can you please take a look at the property manager view/edit page for styling consistency while you're finishing off this PR? It seems some spacing around the form is missing, but it's present for the tenant view/edit page and the property view/edit page.

**Comment by Protopaco** [comment]
> @Protopaco, can you please take a look at the property manager view/edit page for styling consistency while you're finishing off this PR? It seems some spacing around the form is missing, but it's present for the tenant view/edit page and the property view/edit page.

No problem.  I have some edits ready to bring the styling in line with the other "Edit Property" and "Edit Tenant" pages.  Do we want to push those changes to this branch?   It seems probably that the changes I made on this PR will need to be ditched.  I would be happy to make a smaller PR for just these changes so they can be added cleanly, if that makes sense.  Thanks!

**Comment by DaveTrost** [comment]
> It seems probably that the changes I made on this PR will need to be ditched. 

Uh-oh ... I didn't notice anything in my review. Is there something else going on that hasn't been mentioned?

**Comment by Protopaco** [comment]
> > It seems probably that the changes I made on this PR will need to be ditched.
> 
> Uh-oh ... I didn't notice anything in my review. Is there something else going on that hasn't been mentioned?

It seems I missed a couple of comments in the middle.  I made these color changes based on the accessibility audit.  It had been so long I had assumed that these changes would be scrapped and we would start over under direction of the design team.  I will remember to bring these up at the meeting tomorrow, take the feedback and finish this off. 

It does feel like the specific  style changes in Property Manager could be handled separately, though.  They are pretty straight forward and dry.    Thanks!

**Comment by DaveTrost** [comment]
> It does feel like the specific style changes in Property Manager could be handled separately, though. They are pretty straight forward and dry. Thanks!

I agree with that reasoning. I opened a new ticket for this.

**Comment by Protopaco** [comment]
> I agree with that reasoning. I opened a new ticket for this.

**Pull request closed without merging**
