### PR TITLE
Tables are now responsive, vertically stacking table columns on mobile

### PR DESCRIPTION
**Pull request by beekman**
### What issue is this solving?
548, unusable tables on mobile.

### Any helpful knowledge/context for the reviewer?
None.

### Please make sure you've attempted to meet the following coding standards
- [X ] Code builds successfully
- [ X] Code has been tested and does not produce errors
- [ X] Code is readable and formatted
- [X ] There isn't any unnecessary commented-out code
- [X ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Review by Chris-Boe — CHANGES_REQUESTED** [review]
I think we'll still need to add some overflow-x css options to allow the tables to be horizontally scrolled:
image

**Comment by beekman** [comment]
I think you should see something more like this, once I've updated the SCSS target to work for this structure as well as that used on the dashboard...
Screen Shot 2021-03-24 at 7 52 00 PM

**Comment by htharker42** [comment]
image
It also looks like there may be some overflow issue we will want to address

**Comment by beekman** [comment]
> It also looks like there may be some overflow issue we will want to address

Looks like I need to add a second target for the specific DOM structure used on that page, my SCSS target was probably too specific to catch that page. Thanks, I'll update the SCSS to vertically stack both table formats' rows.

**Comment by beekman** [comment]
@Chris-Boe the Tickets module is filled with hard-wired widths on the table headers. Obviously, this approach doesn't work well with mobile. Could you see any problems with removing all of these from the views/tickets/tickets.jsx code?
```
headerStyle: () => {
      return { width: "20%" };
    }
```

**Comment by Chris-Boe** [comment]
> @Chris-Boe the Tickets module is filled with hard-wired widths on the table headers. Obviously, this approach doesn't work well with mobile. Could you see any problems with removing all of these from the views/tickets/tickets.jsx code?
> 
> ```
> headerStyle: () => {
>       return { width: "20%" };
>     }
> ```

The percent widths should work for a responsive app.... since the percent applies to whatever is inherited, maybe there is something further up in the DOM tree that is setting the width and preventing the table from getting smaller?

**Review by Chris-Boe — CHANGES_REQUESTED** [review]
We might want to take a different approach for the larger tables. The columns stacking on each other makes I think a  worse mobile experience than horizontal scrolling. It's especially confusing when some columns are missing data, so the next column's data fills left and looks mislabeled.
image

**Comment by beekman** [comment]
> We might want to take a different approach for the larger tables. The columns stacking on each other makes I think a worse mobile experience than horizontal scrolling. It's especially confusing when some columns are missing data, so the next column's data fills left and looks mislabeled.

I have been thinking the same thing, but I'm glad I had you take a look first to confirm my impression that it was the wrong way to go. I'm going to return to my original idea to make the tables horizontally scroll like traditional responsive bootstrap tables for now. And down the road we can explore more fancy approaches that hide and show fields based on screen size and selection state.

**Pull request closed without merging**
