### PR TITLE
POST method removed from email

### PR DESCRIPTION
**Pull request by rajdama**
### What issue is this solving?
Removing post method from email resources.

### CODE REVIEW

**Comment by rajdama** [comment]
@NickSchimek  Is it correct ?

**Comment by aedwardg** [comment]
@rajdama,
Issue #644 is regarding updating the Email resource in the backend.
Please take a look at the backend repository located here:
https://github.com/codeforpdx/dwellinglybackend

**Comment by rajdama** [comment]
> @rajdama,
> Issue #644 is regarding updating the Email resource in the backend.
> Please take a look at the backend repository located here:
> https://github.com/codeforpdx/dwellinglybackend
> 

Ohh ok got it 👍

**Comment by aedwardg** [comment]
Great! I'm going to close this PR then.
Look forward to your PR in the backend repo 🙂

**Pull request closed without merging**
