### PR TITLE
feat: add current password field on settings change

### PR DESCRIPTION
**Pull request by jumperck**
refs: #768

### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR.

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? n
Any special requirements to test? n

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Comment by jumperck** [comment]
@NickSchimek I've tried to update the test for this change and a couple of things I noticed.
There is a method being added on the `userContext` called `apiCall` this method depends on the `axios` and `Toast` on the `App.jsx`file.
In order to test it I think the best way is to extract this `apiCall` to a separated file where we can verify if the `Toast` and `axios` were called.
But that will require a huge regression test since this method is used by all component on the app that integrate with the api.

My suggestion is to keep it simple and test just the unit, mock the `apiCall` and just verify if the parameters were properly sent. With that I few scenarios will change on the test.

What are your thoughts on it?

**Comment by NickSchimek** [comment]
This looks good and works on my end.
Can you rebase the branch and force push? Including some instructions incase your not familiar with it.

`git checkout development`
`git pull upstream development` or `git pull origin development` depending on your setttings.

```
git checkout feature/issue-768-account-details-send-password
git rebase development
```

**Comment by NickSchimek** [comment]
As far as testing. I wouldn't worry about unit testing since there isn't any logic that I know of that needs to be tested here. 
I would prefer to have a system test (Cypress) over a unit test here.

You can see an example of testing the toast message in `cypress/integration/dashboard/request_access.spec.js`

**Comment by KaueReinbold** [comment]
> As far as testing. I wouldn't worry about unit testing since there isn't any logic that I know of that needs to be tested here. I would prefer to have a system test (Cypress) over a unit test here.
> 
> You can see an example of testing the toast message in `cypress/integration/dashboard/request_access.spec.js`

**Review by NickSchimek — APPROVED** [review]

**Pull request merged**
