### PR TITLE
Remove 'history.push('route') routing and add routing using <Link> from react-router-dom where appropriate. Resolve for issue #224

### PR DESCRIPTION
**Pull request by marcusjensen15**
Resolve for issue #224

### CODE REVIEW

**Review by Chris-Boe — CHANGES_REQUESTED** [review]
Looks like the Add New button on the Join Staff page got some weird styling to it compared to our normal Add New buttons 
image

**Comment by Chris-Boe** [comment]
Other than that styling and the merge conflicts, it looks good!

**Comment by marcusjensen15** [comment]
Fixed button on the join staff page so it matches the others. resolved merge conflict.

**Review by Chris-Boe — APPROVED** [review]
Looks great! Thanks for updating all these

**Pull request merged**
