### PR TITLE
adds ability to update tenant, assigned, and urgency for tickets

### PR DESCRIPTION
**Pull request by Protopaco**
### What issue is this solving?
#527 - adds ability to update tenant, assigned, and urgency for tickets

This is issue is unfinished, but I need some guidance before I can complete it.  
I wanted to give you an idea of the direction I was going, and address styling.

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary?
Any special requirements to test?

### Please make sure you've attempted to meet the following coding standards
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

### CODE REVIEW

**Comment by Protopaco** [comment]
@Chris-Boe 
I feel like I did the rebase correctly, it was my least disastrous attempt.  That being said, I'm nervous about all of those commits that were incorporated into the PR.  

The build seems to have survived the process however, and appears to be working as I intended.  All of the functionality is there, I just wanted to confirm that you were ok with my implementation of the searchable-drop down-inputs.  I tried using existing solutions but they were too big for this limited space.  

I also think the edit pen is a little awkward in its current location.  I tried a bunch of ways to tweak it, but I feel like the icon is just too large for the space.  In no was a deal breaker, just something to look at. 

Thanks!

**Comment by Chris-Boe** [comment]
> @Chris-Boe
> I feel like I did the rebase correctly, it was my least disastrous attempt. That being said, I'm nervous about all of those commits that were incorporated into the PR.
> 
> The build seems to have survived the process however, and appears to be working as I intended. All of the functionality is there, I just wanted to confirm that you were ok with my implementation of the searchable-drop down-inputs. I tried using existing solutions but they were too big for this limited space.
> 
> I also think the edit pen is a little awkward in its current location. I tried a bunch of ways to tweak it, but I feel like the icon is just too large for the space. In no was a deal breaker, just something to look at.
> 
> Thanks!

Hmm I'm not sure what happened with the rebase to bring all these commits back. It might be possible to get rid of those by closing and re-opening the PR, I've seen that fix it before so it might be worth a try.

**Review by Chris-Boe — DISMISSED** [review]
This looks pretty good so far, there are just some styling issues. I think the placement of the edit pencil could be a bit more in line with the title, and we could make it have the filled in circle around it like on the other edit pages. The rest of the styling might have got a bit jumbled with the rebase, things seem to have gotten pushed down in the right column:

image

**Comment by Protopaco** [comment]
> > @Chris-Boe
> > I feel like I did the rebase correctly, it was my least disastrous attempt. That being said, I'm nervous about all of those commits that were incorporated into the PR.
> > The build seems to have survived the process however, and appears to be working as I intended. All of the functionality is there, I just wanted to confirm that you were ok with my implementation of the searchable-drop down-inputs. I tried using existing solutions but they were too big for this limited space.
> > I also think the edit pen is a little awkward in its current location. I tried a bunch of ways to tweak it, but I feel like the icon is just too large for the space. In no was a deal breaker, just something to look at.
> > Thanks!
> 
> Hmm I'm not sure what happened with the rebase to bring all these commits back. It might be possible to get rid of those by closing and re-opening the PR, I've seen that fix it before so it might be worth a try.

I tried closing and reopening the PR.  It doesn't appear to have helped.  Should I just trash this PR and start over fresh with just the code?

**Comment by Protopaco** [comment]
> This looks pretty good so far, there are just some styling issues. I think the placement of the edit pencil could be a bit more in line with the title, and we could make it have the filled in circle around it like on the other edit pages. The rest of the styling might have got a bit jumbled with the rebase, things seem to have gotten pushed down in the right column:
> 
> image

I had forgotten that we had a custom "TitleAndPen" hook from the other edit pages.  I used that, and tweaked the CSS a bunch to try and accommodate the edit ticket content.  I tried it on three different browsers, and they all seem to be handling the switch alright.  Please let me know if it looks different on your screen.  We might have to change the way the ticket window size is handled.  Thanks!

**Pull request merged**
